version: '3'

services:
  client:
    build: ./client
    ports:
      - "5173:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/temp:/app/temp
    environment:
      - MONGODB_URL=mongodb+srv://soubhagyaraha2:z1voEwvjBiCsBtVS@cluster0.h7domly.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
